### ISSUE TITLE
Set up local folder for backup

### ISSUE THREAD

**Issue by vokshirg** [spilin/capistrano3-postgres#17]
cap postgres:backup:download # Downloads dump to local server(By default stores file in ./tmp/postgres_backup directory)
How could i change default folder for local backups? Thanks )

**Comment by spilin** [comment]
It uses `tmp/#{fetch :postgres_backup_dir}` to store backups. Meaning you can change `postgres_backup` directory by setting `set :postgres_backup_dir, -> { 'new_dir' }`. If you need to change the whole path - we need to make changes to project.
